services:
  ci-runner:
    build:
      context: .
      dockerfile: ci/Dockerfile.test
    working_dir: /src
    volumes:
      - .:/src
      - /var/run/docker.sock:/var/run/docker.sock
      - cargo-registry:/root/.cargo/registry
      - cargo-git:/root/.cargo/git
      - target:/src/target
    environment:
      CARGO_TERM_COLOR: always
      LNURL_TEST_POSTGRES_URL: postgres://user:password@postgres:5432/lnurl
      PROTOC_INCLUDE: /usr/include

  integration-tests:
    extends:
      service: ci-runner
    depends_on:
      postgres:
        condition: service_healthy
    command: >-
      bash -lc 'env -u LNURL_TEST_POSTGRES_URL cargo test --locked &&
      cargo test --locked postgres_tests -- --test-threads=1'

  e2e-tests:
    extends:
      service: ci-runner
    environment:
      CARGO_TERM_COLOR: always
      COMPOSE_PROJECT_NAME: blink-lnurl-server-e2e
      PROTOC_INCLUDE: /usr/include
    command: make e2e

volumes:
  cargo-registry:
  cargo-git:
  target:
