apiVersion: vendir.k14s.io/v1alpha1
kind: Config

# Relative to ci/
directories:
  - path: ./vendor
    contents:
      - path: .
        git:
          url: https://github.com/blinkbitcoin/concourse-shared.git
          ref: fb262c23f1957798af31226f6aede9fbbe0d4f13
        includePaths:
          - shared/ci/**/*
        excludePaths:
          - shared/ci/**/nodejs-*
          - shared/ci/**/tofu-*
        newRootPath: shared/ci
